feat(députés): add responsabilités
regardscitoyens/NosDeputes2-front pull request #18
Opened 2022-11-13 21:03 UTC by revolunet

basé sur https://github.com/regardscitoyens/nosdeputes.fr/blob/22304a556635a6ea0cd25db2fa92da872040a838/apps/frontend/modules/parlementaire/templates/_fiche.php#L94

<img width="666" alt="Capture d’écran 2022-11-13 à 22 02 13" src="https://user-images.githubusercontent.com/124937/201544407-2f6e8f90-acbc-49e4-bd87-c48d971c8e5b.png">

2022-11-13 21:09 UTC, RouxRC commented
Sur le screenshot il y a une erreur manifeste : tu as pris les organismes de type "groupe" au lieu de "groupes" pour les groupes d'études et affiche le groupe politique et non les groupes d'études

2022-11-13 21:42 UTC, revolunet commented
corrigé merci

2022-11-13 21:46 UTC, RouxRC commented
Sinon on avait quelques exceptions pour mettre en avant certaines fonctions exceptionnelles qui méritaient plus d'attention genre les présidents, questeurs, rapporteurs généraux etc, mais il y a certainement moyen de faire ça mieux et ça mérite probablement un peu de réflexion de design

2022-11-13 22:25 UTC, implicitdef requested changes
des petits retours

2022-11-13 22:25 UTC, implicitdef commented on src/lib/queryDeputeResponsabilites.ts
> +  type: string
tu peux typer ça précisément ? il n'y a que 3 valeurs ;P

2022-11-13 22:25 UTC, implicitdef commented on src/lib/queryDeputeResponsabilites.ts
> +  fonction: string | null
Ne devrait pas être nullable
Si tu enlèves le null et tu fais un innerJoin au lieu d'un leftJoin dans la requête, ça passe

2022-11-13 22:25 UTC, implicitdef commented on src/lib/queryDeputeResponsabilites.ts
> +        .orWhere(sql`parlementaire_organisme.fin_fonction >= NOW()`),
tu as vu des dates de fonction qui pouvaient être dans le futur ?
si oui cela veut dire qu'il y a une erreur ailleurs dans le code, quand j'affiche les membres des organismes/groupes, je crois n'avoir fait le check que sur NULL

2022-11-13 22:25 UTC, implicitdef commented on src/pageModules/deputeFiche/DeputeFiche.render.tsx
> +  const isResponsabiliteParlementaire = (
cette fonction peut être extractée, pas besoin de nester

2022-11-13 22:58 UTC, revolunet commented on src/lib/queryDeputeResponsabilites.ts
> +        .orWhere(sql`parlementaire_organisme.fin_fonction >= NOW()`),
en effet il n'y en a pas 🤔

2022-11-13 23:10 UTC, revolunet commented
@RouxRC 

> Sur le screenshot il y a une erreur manifeste : tu as pris les organismes de type "groupe" au lieu de "groupes" pour les groupes d'études et affiche le groupe politique et non les groupes d'études
Le groupe politique apparait dans le cartel du dessus sur ND

OK, mais dans la base, je ne vois aucun item de type "groupes" dans la table organismes.

2022-11-13 23:48 UTC, RouxRC commented
Ha oui bien vu, c'est du au fait que l'AN a arrêté de les donner dans les pages des députés, du coup on ne les a plus, il faudrait théoriquement les parser depuis les pages des groupes ce qui n'a jamais été fait depuis la modif côté AN
À vous de voir si vous voulez tout de même laisser dnas le code la gestion en vue d'un rajout un jour ou non

2022-11-13 23:51 UTC, RouxRC commented
cf https://www.nosdeputes.fr/organismes/groupes qui est vide
je mets un pointeur dans l'issue (ancienne...) dédiée côté ND

2022-11-14 09:23 UTC, implicitdef commented
FYI @revolunet tu as bien les "groupes" dans le dump de la législature précédente
moi j'ai importé les deux dumps en local et je switche régulièrement de l'un à l'autre pour tester certains trucs

2022-11-14 18:29 UTC, implicitdef approved these changes

2022-11-14 18:54 UTC, implicitdef commented
Je viens de voir un souci dans ton parsing pour /farida-amrani

Elle a comme responsabilités :

```
Fonctions judiciaires, internationales ou extra-parlementaires :
Des comptes de la sécurité sociale (membre titulaire)
```
Le "Commission ..." a sauté mais ici on ne comprend pas

2022-11-14 21:15 UTC, revolunet commented
On peut peut être laisser le nom original pour l'instant ?

2022-11-14 21:41 UTC, implicitdef commented
> On peut peut être laisser le nom original pour l'instant ?

Oui oui laisser le nom entier ça me va très bien

2022-11-15 08:12 UTC, merged