feat(seance)
regardscitoyens/NosDeputes2-front pull request #21
Opened 2022-11-15 19:50 UTC by gplassard

![image](https://user-images.githubusercontent.com/2485407/202010989-66cc0901-1c00-4b2b-a7e3-f41129292d56.png)

J'ai pas encore tout à fait fini mais j'ouvre la PR en draft pour avoir déjà des retours :)

Clairement le css n'est pas mon fort et j'avais encore jamais utilisé tailwind donc j'ai un peu fait au feeling

Il y aussi quelques trucs que je sais pas trop comment faire, typiquement là on a un seul fichier css pour les imports de tailwind et le style qui est géré direct en props dans react. Je voulais faire en sorte de cacher les liens et de les afficher qu'au survol du bloc (comme actuellement) mais ça ne peut se faire qu'avec du css et pas des style inline je crois ?

Je me suis également noté quelques todos

2022-11-15 21:48 UTC, implicitdef commented
hello, merci pour ta PR, ça m'a l'air très bien à première vue (pas encore lu le code)
Pour moi je ne me prends pas la tête à reproduire finement l'UX, on ne sait pas encore si on veut reprendre vraiment nosdeputes à l'identique ou pas. Et là par exemple là les liens qui s'affiche qu'au survol je ne pense pas que ce soit fou en termes d'UX, on pourra sûrement trouver quelque chose de plus simple/standard.

Peut-être tu peux juste mettre un background à certaines divs pour que ce soit un poil plus lisible ? soit pour chaque intervention, soit pour chaque section, soit pour toute la séance, à toi de voir

Pour répondre sur Tailwind, oui le principe c'est de tout faire avec leurs classes autant que possible. On s'y fait très vite, c'est facile de chercher dans leur doc pour trouver les bonnes classes et il y a une extension vscode qui aide avec l'autocomplétion. Ils ont un système pour les 'hover' https://tailwindcss.com/docs/hover-focus-and-other-states mais effectivement je ne suis pas sûr que tu puisses altérer un élément enfant au survol d'un parent.

2022-11-15 22:39 UTC, implicitdef requested changes
gros gros taf merci à toi tu as dû en baver
je n'ai pas eu le temps de vraiment décortiquer la logique des queries et de l'affichage, j'essaierai de repasser plus tard

2022-11-15 22:39 UTC, implicitdef commented on docker-compose.yaml
> +  nosdeputes_data:
ça change quoi par rapport à l'existant (je ne suis pas très calé en docker) ?

2022-11-15 22:39 UTC, implicitdef commented on src/components/MyLink.tsx
> +  title?: string
inutilisé

2022-11-15 22:39 UTC, implicitdef commented on src/components/SeanceSummary.tsx
> +  style?: CSSProperties
tu n'utilises ce Component qu'une seule fois, autant hardcoder la margin dedans non ?
et il veut mieux utiliser les classes tailwind autant que possible stp

2022-11-15 22:39 UTC, implicitdef commented on src/components/SeanceSummary.tsx
> +          <ul key={section.id + '_subsections'} style={{ marginLeft: '30px' }}>
hmmm tu as un `<ul>` qui peut avoir comme enfants directs à la fois des `<li>` et des `<ul>`... je pense que tu es censé imbriquer le sous `<ul>` dans ton `<li>`

2022-11-15 22:39 UTC, implicitdef commented on src/lib/seanceSummary.ts
> +export function seanceSummary(sections: SeanceSection[]): SeanceSummary {
on a un `seanceSummary` et `SeanceSummary`. Est-ce qu'on peut renommer le premier en `buildSeanceSummary` par exemple (la fonction et le fichier) ?

2022-11-15 22:39 UTC, implicitdef commented on src/lib/seanceSummary.ts
> +  for (const section of uniqBy(sections, s => s.id)) {
cet algo est surprenant, c'est repris du php ?
j'ai déjà bossé sur les sections sur une autre page (dossiers je crois) et la notion de lien entre les section et sous sections était clairement présente via le champ `section_id` dans les sections :
- par exemple une section A a comme section_id B, donc A est fille B
- et la section B a comme `section_id` B, elle-même, donc B est une section mère

2022-11-15 22:39 UTC, implicitdef commented on src/pageModules/seanceFiche/SeanceFiche.render.tsx
> +import { groupBy, mapValues } from 'lodash'
attention aux imports lodash, comme ça tu importes tout lodash (et tu es sur une page de rendu, c'est téléchargé par le client)
si tu fais comme ça :
`import groupBy from 'lodash/groupBy` c'est casse pieds à écrire mais tu n'importes que le strict nécessaire

2022-11-15 22:39 UTC, implicitdef commented on src/pageModules/seanceFiche/SeanceFiche.render.tsx
> +        // pas joli de faire un effet de bord comme ça :/
non pas joli ;p 
je lis un peu rapidement là, c'est un peu trop complexe pour que j'arrive à suivre
Peut-être que si tu réorganisais tes données côté server exactement comme tu en as besoin, tu aurais moins de choses à faire dans le render ?
Si tu ne t'en sors pas dis moi et je creuserai

2022-11-15 22:39 UTC, implicitdef commented on src/pageModules/seanceFiche/SeanceFiche.server.tsx
> +    .leftJoin('intervention', 'seance.id', 'intervention.seance_id')
remarque générale (je ne sais pas si ça s'applique sur ce fichier, à toi de voir) : dans le php je trouve qu'ils font beaucoup de `leftJoin` là où en fait c'est souvent plus logique de faire des `innerJoin`. Avec les leftJoin on se retrouve souvent à gérer des row avec des champs null qui ne devraient pas arriver ou dont on ne peut rien faire de toute façon.

2022-11-15 22:39 UTC, implicitdef commented on src/pageModules/seanceFiche/SeanceFiche.types.ts
> +  // TODO remove prefix ?
:) oui moi je renomme beaucoup les champs dans les query (`X as Y`) pour atterir sur des noms plus pertinents

2022-11-17 12:09 UTC, gplassard commented
Hello, merci pour tes retours je regarde tout ça :)

2022-11-17 12:10 UTC, gplassard commented on docker-compose.yaml
> +  nosdeputes_data:
rien du tout, mon IDE qui tenait absolument à ce qu'il y ait une ligne vide en fin de fichier et j'ai fini par craquer, je l'enleve

2022-11-17 12:14 UTC, gplassard commented on src/components/MyLink.tsx
> +  title?: string
Je m'en suis servi ici https://github.com/regardscitoyens/NosDeputes2-front/blob/seance/src/pageModules/seanceFiche/SeanceFiche.render.tsx#L238-L240 pour faire l'attribution de l'image que j'ai récupéré sur wikipedia. En récupérant le modèle qu'ils proposent : https://commons.wikimedia.org/wiki/File:Unknown_person.jpg

Après effectivement en terme visuel d'interaction ça ne sert à rien car j'ai un autre title sur l'image qui prend le dessus et/ou c'est pas supporté de mettre un title sur un a ?

2022-11-17 12:15 UTC, gplassard commented on src/components/SeanceSummary.tsx
> +          <ul key={section.id + '_subsections'} style={{ marginLeft: '30px' }}>
J'ai repris le dom actuel et j'ai l'impression que c'est la façon "correcte" de faire https://developer.mozilla.org/fr/docs/Web/HTML/Element/ul#liste_imbriqu%C3%A9e

2022-11-17 12:22 UTC, gplassard commented on src/lib/seanceSummary.ts
> +  for (const section of uniqBy(sections, s => s.id)) {
globalement oui je dirais https://github.com/gplassard/nosdeputes.fr/blob/master/apps/frontend/modules/intervention/templates/seanceSuccess.php#L29-L36

effectivement là ça se base sur le fait que l'ordre dans lequel on traite les éléments soit 
parent1, enfants de parent1, parent2, enfants de parent2, .... ce qui est nécessaire dans l'implementation actuelle car le dom est construit en mode concaténation ce qui est une contrainte dont on peut se libérer ici car on cherche à construire l'objet qui sera utilisé ensuite pour construite les composants react. Ca rendrait le code plus robuste et plus cohérent avec le format de données, je vais faire le changement

2022-11-17 12:24 UTC, gplassard commented on src/pageModules/seanceFiche/SeanceFiche.render.tsx
> +import { groupBy, mapValues } from 'lodash'
de mémoire la syntaxe d'import comme ça permet théoriquement le treeshaking mais ces packages lodash ne sont pas spécialement treeshakable c'est ça ?

2022-11-17 12:25 UTC, gplassard commented on src/pageModules/seanceFiche/SeanceFiche.render.tsx
> +        // pas joli de faire un effet de bord comme ça :/
Oui bonne idée, je vais déplacer ça côté serveur et passer des props plus simples à utiliser côté client

2022-11-17 12:25 UTC, gplassard commented on src/pageModules/seanceFiche/SeanceFiche.server.tsx
> +    .leftJoin('intervention', 'seance.id', 'intervention.seance_id')
oui je me suis fait aussi la réflexion, ça marche je vais regarder

2022-11-17 12:28 UTC, gplassard commented on src/pageModules/seanceFiche/SeanceFiche.types.ts
> +  // TODO remove prefix ?
okay ça marche, je vais faire ça aussi !

Par contre pour faire en sorte que les données des tables jointes soient dans un nested object ya pas de solution magique j'imagine ? (faire un attribut "parlementaire" avec les propriétés nom / slug / id_an, ça permettrait aussi d'être plus précis sur les types en disant que si le parlementaire est présent alors tous les champs sont remplis).

Après je peux faire un map sur le résultat et construire mon objet "à la main" aussi c'est pas un soucis

2022-11-18 18:33 UTC, implicitdef commented on src/components/MyLink.tsx
> +  title?: string
Je voulais dire que ce `title` que tu passes au `<MyLink`, le `<MyLink` n'en fait rien, du coup il n'apparait pas dans le HTML. Et oui je ne crois pas que l'attribut title sur les <a> existe, et oui celui de l'image devrait suffire.

2022-11-18 18:44 UTC, implicitdef commented on src/components/SeanceSummary.tsx
> +          <ul key={section.id + '_subsections'} style={{ marginLeft: '30px' }}>
Ah curieux, ok

2022-11-18 18:46 UTC, implicitdef commented on src/pageModules/seanceFiche/SeanceFiche.types.ts
> +  // TODO remove prefix ?
C'est ça, pas de solution magique. Kysely ne fait que du SQL, le résultat c'est juste un tableau, comme une requête SQL. Si tu veux faire ça tu es obligé de retravailler le résultat en JS à la mano.

2022-11-19 21:21 UTC, gplassard commented on src/components/MyLink.tsx
> +  title?: string
ah oui 🤦 
merci !
Je l'ai passé correctement du coup, effectivement je sais pas à quel point c'est pertinent mais vu que c'est la façon dont wikimedia demande de référencer cette image lorsqu'on l'utilise je me dis que c'est mieux ?

2022-11-20 10:37 UTC, implicitdef commented on src/components/MyLink.tsx
> +  title?: string
OK alors, je comprends on peut faire ça.
(`title` en fait existe sur tous les éléments HTML je ne savais pas https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)

2022-12-03 11:44 UTC, implicitdef commented
@gplassard est-ce que tu penses avoir le temps de terminer cette PR ?

2022-12-28 20:28 UTC, implicitdef commented
Hello @gplassard 
Il y a eu du grand chamboulement sur main depuis que cette PR a démarré
J'ai switché sur une nouvelle DB et je ne sais pas encore comment je vais récupérer le contenu des séances, mais ce sera forcément différent. Je vais fermer cette PR mais je la garde sous le code. Je m'en servirais probablement comme référence pour une nouvelle implémentation. Peut-être que je pourrai reprendre le rendu JSX tel quel avec les nouvelles données.

2022-12-28 20:28 UTC, closed without merging